apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fargate-bliz-usw2
  region: us-west-2
iam:
  withOIDC: true
fargateProfiles:
  - name: defaultfp
    selectors:
      - namespace: default
      - namespace: kube-system
      - namespace: amazon-cloudwatch
      - namespace: aws-observability
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
