apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fg-atvi-arm-us-west-2
  region: us-west-2

nodeGroups:
  - name: arm-ng-1
    labels:
      project: atvi
    desiredCapacity: 1
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    instancesDistribution:
      instanceTypes: ["c6g.xlarge","c6gn.xlarge","c6gd.xlarge","t4g.xlarge","m6gd.xlarge","m6g.xlarge","c6gd.2xlarge","c6gn.2xlarge","c6g.2xlarge","r6gd.xlarge","r6g.xlarge","m6gd.2xlarge","m6g.2xlarge","t4g.2xlarge","c6g.4xlarge","c6gd.4xlarge","c6gn.4xlarge"]
fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
      - namespace: karpenter




