apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fg-bliz-us-west-2
  region: us-west-2

nodeGroups:
  - name: ng-1
    labels:
      project: bliz
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    instanceType: m5.large
    desiredCapacity: 1
fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
      - namespace: amazon-cloudwatch
