apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: fluent-bit
    version: v1
  name: fluent-bit
  namespace: amazon-cloudwatch
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit
  template:
    metadata:
      labels:
        k8s-app: fluent-bit
        version: v1
    spec:
      containers:
      - env:
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              key: logs.region
              name: fluent-bit-cluster-info
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              key: cluster.name
              name: fluent-bit-cluster-info
        - name: HTTP_SERVER
          valueFrom:
            configMapKeyRef:
              key: http.server
              name: fluent-bit-cluster-info
        - name: HTTP_PORT
          valueFrom:
            configMapKeyRef:
              key: http.port
              name: fluent-bit-cluster-info
        - name: READ_FROM_HEAD
          valueFrom:
            configMapKeyRef:
              key: read.head
              name: fluent-bit-cluster-info
        - name: READ_FROM_TAIL
          valueFrom:
            configMapKeyRef:
              key: read.tail
              name: fluent-bit-cluster-info
        - name: HOST_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CI_VERSION
          value: k8s/1.3.8
        image: 498254202105.dkr.ecr.us-west-2.amazonaws.com/aws-for-fluent-bit:x86-2.10.0
        #image: amazon/aws-for-fluent-bit:2.10.0
        imagePullPolicy: Always
        name: fluent-bit
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 500m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/fluent-bit/state
          name: fluentbitstate
        - mountPath: /var/log
          name: varlog
          readOnly: true
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /fluent-bit/etc/
          name: fluent-bit-config
        - mountPath: /run/log/journal
          name: runlogjournal
          readOnly: true
        - mountPath: /var/log/dmesg
          name: dmesg
          readOnly: true
      #schedulerName: default-scheduler
      schedulerName: fargate-scheduler
      serviceAccount: fluent-bit
      serviceAccountName: fluent-bit
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /var/fluent-bit/state
          type: ""
        name: fluentbitstate
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
      - configMap:
          defaultMode: 420
          name: fluent-bit-config
        name: fluent-bit-config
      - hostPath:
          path: /run/log/journal
          type: ""
        name: runlogjournal
      - hostPath:
          path: /var/log/dmesg
          type: ""
        name: dmesg
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
