apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: tenant1
spec:
  limits:
    resources:
      cpu: 100k
  provider:
    apiVersion: extensions.karpenter.sh/v1alpha1
    instanceProfile: KarpenterNodeInstanceProfile-fg-atvi-arm-us-west-2
    kind: AWS
    securityGroupSelector:
      kubernetes.io/cluster/fg-atvi-arm-us-west-2: '*'
    subnetSelector:
      kubernetes.io/cluster/fg-atvi-arm-us-west-2: '*'
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values: 
    - on-demand
#    - spot
  - key: kubernetes.io/arch
    operator: In
    values:
    - arm64
  ttlSecondsAfterEmpty: 30
