apiVersion: apps/v1
kind: Deployment
metadata:
  name: appupdate
  labels:
    app: appupdate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appupdate
  template:
    metadata:
      labels:
        app: appupdate
    spec:
      nodeSelector:
        eks.amazonaws.com/compute-type: fargate
        #karpenter.sh/provisioner-name: tenant1
      containers:
      - name: appupdate
        image: 652773884901.dkr.ecr.us-west-2.amazonaws.com/pybusybox:x86-0.10
        imagePullPolicy: Always
        env:
          - name: SLEEP_TIME
            value: "5"
      terminationGracePeriodSeconds: 120
