apiVersion: apps/v1
kind: Deployment
metadata:
  name: appinsert
  labels:
    app: appinsert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appinsert
  template:
    metadata:
      labels:
        app: appinsert
    spec:
      nodeSelector:
        eks.amazonaws.com/compute-type: fargate
        #karpenter.sh/provisioner-name: tenant1
      containers:
      - name: appinsert
        image: 498254202105.dkr.ecr.us-west-2.amazonaws.com/pybusybox:x86-0.2
        imagePullPolicy: Always
        env:
          - name: SLEEP_TIME
            value: "5"
      terminationGracePeriodSeconds: 120
